# South Barnegat Bay Onshore Wind Model Prediction with the Use of Long Short-Term Memory Neural Networks - Graphing

In [14]:
import pandas as pd
import matplotlib.pyplot as plt

In [15]:
#Open data as csv
data = pd.read_csv("csv/CLEAN.csv")

#Convert to datetime
#Convert data into Date time and create date filter
data['Date'] = pd.to_datetime(data['Date'])
data['Date'] = data['Date'] + pd.to_timedelta(data["Hr"], unit="h")
data.drop('Hr', axis=1, inplace=True)

In [16]:
#Open data as csv
data_p = pd.read_csv("csv/all_predictions.csv")

In [17]:
data.head()

,Date,Mainland Air Temp,Humidity (%),Direction (A),Wind Speed (A),Gusting,Atmospheric Pressure (IN),Precipitation Rate,Bay Temp,Salinity,LBI Air Temp,Ocean Temp,Onshore,upwelling_flag
0,2025-06-02 00:00:00,13.9,68.0,10,3.8,6.0,29.86,0.00,17.47,27.70,17.8,14.3,0,0
1,2025-06-02 01:00:00,13.6,74.0,12,4.0,6.2,29.88,0.00,17.49,28.20,17.5,14.2,0,0
2,2025-06-02 02:00:00,12.7,78.0,11,3.0,5.4,29.88,0.01,17.27,27.93,16.2,14.2,0,0
3,2025-06-02 03:00:00,11.3,84.0,12,2.7,6.1,29.88,0.00,17.26,28.41,14.9,14.2,0,0
4,2025-06-02 04:00:00,10.3,87.0,13,2.0,3.8,29.89,0.00,16.82,28.42,13.7,14.2,0,0

In [18]:
data_p.head()

,Date,Mainland Air Temp,Humidity (%),Direction (A),Wind Speed (A),Gusting,Atmospheric Pressure (IN),Precipitation Rate,Bay Temp,Salinity,LBI Air Temp,Ocean Temp,Onshore,upwelling_flag,upwelling_pred_naive,onshore_pred_direction,wind_direction_pred_naive,wind_speed_pred_linear,wind_gust_pred_linear,Wind_pred_warning
0,2025-06-02 00:00:00,13.9,68.0,10,3.8,6.0,29.86,0.00,17.47,27.70,17.8,14.3,0,0,NaN,NaN,NaN,NaN,NaN,False
1,2025-06-02 01:00:00,13.6,74.0,12,4.0,6.2,29.88,0.00,17.49,28.20,17.5,14.2,0,0,NaN,NaN,NaN,NaN,NaN,False
2,2025-06-02 02:00:00,12.7,78.0,11,3.0,5.4,29.88,0.01,17.27,27.93,16.2,14.2,0,0,NaN,NaN,NaN,NaN,NaN,False
3,2025-06-02 03:00:00,11.3,84.0,12,2.7,6.1,29.88,0.00,17.26,28.41,14.9,14.2,0,0,NaN,NaN,NaN,NaN,NaN,False
4,2025-06-02 04:00:00,10.3,87.0,13,2.0,3.8,29.89,0.00,16.82,28.42,13.7,14.2,0,0,NaN,NaN,NaN,NaN,NaN,False